// @AI-Generated by Copilot 2026-04-28 18:00:00
namespace Inkslab.Expressions.Tests
{
    /// <summary>
    ///     虚拟成员（MemberRef）绑定接口。动态生成的类型在含有跨层级 MemberRef 时实现该接口。
    ///     调用 <see cref="BindMemberRefs()"/> 后，对象树中所有跨层级 MemberRef 属性会被赋值为目标祖先成员的当前值。
    /// </summary>
    public interface IMemberRefBinder
    {
        /// <summary>
        ///     根入口：分配 <c>deepObj</c> 数组并以 <c>level=0</c> 调用递归重载。
        ///     <para>仅在根类型上调用有效；嵌套类型不应直接调用此重载。</para>
        /// </summary>
        void BindMemberRefs();
    }
}
// @AI-Generated-End
