using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Text.RegularExpressions;
using Inkslab.Emitters;
using Inkslab.Map;

namespace Inkslab.Expressions.Tests
{
    /// <summary>
    /// 类型生成器。
    /// </summary>
    public class TypeGenerator : ITypeGenerator
    {
        private static readonly Regex _regex = new(@"[^A-Za-z0-9_]");

        private static readonly HashSet<string> _strings = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "BusinessLine",
            "Offset",
            "Take"
        };

        // @AI-Generated by Copilot 2026-04-28 18:00:00
        private static readonly MethodInfo _referenceEqualsMethod =
            typeof(object).GetMethod(nameof(object.ReferenceEquals), new[] { typeof(object), typeof(object) })!;
        // @AI-Generated-End

        private readonly ModuleEmitter _emitter;

        /// <summary>
        ///     初始化类型生成器。
        /// </summary>
        public TypeGenerator(ModuleEmitter emitter)
        {
            _emitter = emitter;
        }

        // @AI-Generated by Copilot 2026-04-28 18:00:00
        private sealed class ScopePlan
        {
            public AbstractTypeEmitter TypeEmitter;
            public bool IsRoot;
            public int Depth;
            public MethodEmitter BindEntryMethod;
            public MethodEmitter BindRecursiveMethod;
            public MethodEmitter GetSourceMethod;
            public ParameterEmitter DeepObjParam;
            public ParameterEmitter LevelParam;
            public ParameterEmitter SlotParam;
            public List<LocalCrossRef> LocalCrossRefs = new();
            public List<ChildWalk> ChildWalks = new();
            public List<ExportedSource> ExportedSources = new();

            public bool HasWork => LocalCrossRefs.Count > 0 || ChildWalks.Count > 0;
        }

        private sealed class LocalCrossRef
        {
            public FieldEmitter Field;
            public Type PropertyType;
            public ScopePlan TargetScope;
            public int TargetSlot;
        }

        private sealed class ChildWalk
        {
            public FieldEmitter Field;
            public Type PropertyClrType;
            public bool IsArray;
            public MethodEmitter BindMethodEmitter;
        }

        private sealed class ExportedSource
        {
            public string MemberCode;
            public FieldEmitter Field;
            public Type FieldType;
        }

        private sealed class EmitContext
        {
            public List<ScopePlan> AllPlans = new();
            public Dictionary<string, ScopePlan> ScopeByMemberCode = new(StringComparer.Ordinal);
            public Dictionary<string, MethodEmitter> GettersByCode = new(StringComparer.Ordinal);
            public Dictionary<string, FieldEmitter> FieldsByCode = new(StringComparer.Ordinal);
            public Dictionary<string, Type> TypesByMemberCode = new(StringComparer.Ordinal);
        }
        // @AI-Generated-End

        private Type CreateNestedType(AbstractTypeEmitter typeEmitter, MemberInDto parentMember, int level, MemberInDto[] members,
            Dictionary<string, Type> typeCache, ScopePlan currentPlan, EmitContext ctx)
        {
            string prefix = parentMember.Code + ".";
            MemberInDto[] currentLevelMembers = Array.FindAll(members, m => m.Level == level && m.Code.StartsWith(prefix));

            if (currentLevelMembers.Length == 0)
            {
                throw new InvalidOperationException($"No members found at level {level} with prefix {prefix}.");
            }

            if (currentLevelMembers.Length == 1)
            {
                MemberInDto singleMember = currentLevelMembers[0];
                string code = ExtractMemberCode(singleMember.Code, prefix, level);

                if (code == "*")
                {
                    return HandleWildcardMember(typeEmitter, parentMember, singleMember, level, members, typeCache, currentPlan, ctx);
                }
            }

            return parentMember.MemberType == EnumMemberType.Enum
                ? CreateEnumType(currentLevelMembers, parentMember, prefix, level)
                : CreateClassType(typeEmitter, currentLevelMembers, parentMember, prefix, level, members, typeCache, currentPlan, ctx);
        }

        /// <summary>
        ///    创建类型。
        /// </summary>
        /// <param name="namePrefix">名称前缀。</param>
        /// <param name="members">成员。</param>
        /// <param name="baseType">基类型。</param>
        /// <returns>类型。</returns>
        public Type CreateType(string namePrefix, MemberInDto[] members, Type baseType = null)
        {
            ClassEmitter typeEmitter = _emitter.DefineType($"{namePrefix}_{Guid.NewGuid():N}",
                TypeAttributes.Public | TypeAttributes.Class | TypeAttributes.Sealed,
                baseType ?? typeof(object),
                new[] { typeof(IMemberRefBinder) });

            MemberInDto[] currentLevelMembers = Array.FindAll(members, m => m.Level == 0);

            foreach (MemberInDto member in currentLevelMembers)
            {
                if (_strings.Contains(member.Code))
                {
                    throw new InvalidOperationException(
                        $"Member code cannot be one of the reserved keywords: {member.Code} at level 0, full code is {member.Code}.");
                }
            }

            Dictionary<string, Type> typeCache = new(StringComparer.Ordinal);
            EmitContext ctx = new();
            ScopePlan rootPlan = new() { TypeEmitter = typeEmitter, IsRoot = true, Depth = 0 };
            ctx.AllPlans.Add(rootPlan);

            DefineBinderSkeleton(rootPlan);

            AddPropertiesToClass(typeEmitter, currentLevelMembers, string.Empty, 0, members, typeCache, rootPlan, ctx);

            EmitBinderBodies(ctx);

            return typeEmitter.CreateType();
        }

        // @AI-Generated by Copilot 2026-04-28 18:00:00
        private static void DefineBinderSkeleton(ScopePlan plan)
        {
            AbstractTypeEmitter t = plan.TypeEmitter;

            // 递归绑定（程序集内可见，仅 __BindMemberRefs 和 __GetMemberRefSource 之间互调）
            MethodEmitter bindRec = t.DefineMethod("__BindMemberRefs",
                MethodAttributes.Assembly | MethodAttributes.Virtual | MethodAttributes.NewSlot |
                MethodAttributes.Final | MethodAttributes.HideBySig,
                typeof(void));
            plan.DeepObjParam = bindRec.DefineParameter(typeof(object[]), "deepObj");
            plan.LevelParam = bindRec.DefineParameter(typeof(int), "level");
            plan.BindRecursiveMethod = bindRec;

            // 获取源值（程序集内可见）
            MethodEmitter getSrc = t.DefineMethod("__GetMemberRefSource",
                MethodAttributes.Assembly | MethodAttributes.Virtual | MethodAttributes.NewSlot |
                MethodAttributes.Final | MethodAttributes.HideBySig,
                typeof(object));
            plan.SlotParam = getSrc.DefineParameter(typeof(int), "slot");
            plan.GetSourceMethod = getSrc;

            // 显式接口实现：通过 DefineMethodOverride 建立 IMemberRefBinder.BindMemberRefs() 的映射。
            // DefineMethodOverride 内部使用 ObtainAttributes → 标记为 Public，但 CLR 同时调用
            // TypeBuilder.DefineMethodOverride 将其绑定到接口，因此可经 IMemberRefBinder 接口调用。
            MethodInfo entryMethodInfo = typeof(IMemberRefBinder).GetMethod(
                nameof(IMemberRefBinder.BindMemberRefs), Type.EmptyTypes)!;
            MethodEmitter bindEntry = t.DefineMethodOverride(ref entryMethodInfo);
            plan.BindEntryMethod = bindEntry;
        }

        private static void EmitBinderBodies(EmitContext ctx)
        {
            int maxDepth = 0;

            foreach (ScopePlan p in ctx.AllPlans)
            {
                if (p.Depth > maxDepth)
                {
                    maxDepth = p.Depth;
                }
            }

            int deepSize = maxDepth + 1;

            foreach (ScopePlan plan in ctx.AllPlans)
            {
                EmitRecursiveBinderBody(plan);
                EmitGetSourceBody(plan);

                if (plan.IsRoot)
                {
                    EmitRootEntryBody(plan, deepSize);
                }
                else
                {
                    EmitNonRootEntryBody(plan);
                }
            }
        }

        private static void EmitNonRootEntryBody(ScopePlan plan)
        {
            // 嵌套类型不应直接调用 BindMemberRefs() 无参重载；必须由根入口分配 deepObj 后传入。
            plan.BindEntryMethod.Append(Expression.Throw(typeof(NotSupportedException),
                "Nested IMemberRefBinder instances must be reached via the root BindMemberRefs() entry."));
        }

        private static void EmitRootEntryBody(ScopePlan rootPlan, int deepSize)
        {
            MethodEmitter entry = rootPlan.BindEntryMethod;

            VariableExpression deepObj = Expression.Variable(typeof(object[]));
            entry.Append(Expression.Assign(deepObj, Expression.NewArray(deepSize, typeof(object))));

            // 经 MethodEmitter 显式实例调用自身递归方法。
            entry.Append(Expression.Call(
                Expression.This(rootPlan.TypeEmitter),
                rootPlan.BindRecursiveMethod,
                deepObj, Expression.Constant(0)));
        }

        private static void EmitRecursiveBinderBody(ScopePlan plan)
        {
            MethodEmitter bind = plan.BindRecursiveMethod;

            // 底层使用常量下标：Inkslab.Expressions 的 ArrayIndex(arr, exprIdx) 在赋值路径上存在
            // "ldc_i4 local" 误发射问题（本应为 ldloc）；本作用域 level 在编译期与 plan.Depth 重合，直接用常量越过该 bug。
            int depth = plan.Depth;

            // deepObj[depth] = (object)this;
            bind.Append(Expression.Assign(
                Expression.ArrayIndex(plan.DeepObjParam, depth),
                Expression.Convert(Expression.This(plan.TypeEmitter), typeof(object))));

            foreach (LocalCrossRef cross in plan.LocalCrossRefs)
            {
                Expression target = Expression.ArrayIndex(plan.DeepObjParam, cross.TargetScope.Depth);
                Expression call = Expression.Call(target, cross.TargetScope.GetSourceMethod,
                    Expression.Constant(cross.TargetSlot));

                Expression value = cross.PropertyType == typeof(object)
                    ? call
                    : Expression.Convert(call, cross.PropertyType);

                bind.Append(Expression.Assign(cross.Field, value));
            }

            foreach (ChildWalk walk in plan.ChildWalks)
            {
                AppendChildWalk(bind, plan, walk);
            }
        }

        private static void EmitGetSourceBody(ScopePlan plan)
        {
            MethodEmitter get = plan.GetSourceMethod;

            for (int i = 0; i < plan.ExportedSources.Count; i++)
            {
                ExportedSource src = plan.ExportedSources[i];

                Expression fieldRead = src.Field;

                Expression boxed = src.FieldType.IsValueType
                    ? Expression.Convert(fieldRead, typeof(object))
                    : Expression.Convert(fieldRead, typeof(object));

                get.Append(Expression.IfThen(
                    Expression.Equal(plan.SlotParam, Expression.Constant(i)),
                    Expression.Return(boxed)));
            }

            // 槽位未匹配时返回 null（理论上不可达，调用方按编译期分配的槽位询问）。
            get.Append(Expression.Return(Expression.Constant(null, typeof(object))));
        }

        private static void AppendChildWalk(MethodEmitter bind, ScopePlan parentPlan, ChildWalk walk)
        {
            // 子作用域下标由 IL 编译期静态决定；传递给受限于接口签名，但接收方使用自身 Depth 常量读写。
            Expression nextLevel = Expression.Constant(parentPlan.Depth + 1);

            if (walk.IsArray)
            {
                VariableExpression arr = Expression.Variable(typeof(object[]));
                bind.Append(Expression.Assign(arr, Expression.Convert(walk.Field, typeof(object[]))));

                BlockExpression notNullBlock = Expression.Block();

                // ForEach(item, source) 由框架自行选择 for/foreach 形态。
                VariableExpression item = Expression.Variable(typeof(object));
                ForEachExpression forEach = Expression.ForEach(item, arr);
                AppendBindOnInstance(forEach, parentPlan.DeepObjParam, nextLevel, item, walk.BindMethodEmitter);

                notNullBlock.Append(forEach);

                bind.Append(Expression.IfThen(
                    Expression.Not(Expression.Call(_referenceEqualsMethod,
                        new Expression[]
                        {
                            Expression.Convert(arr, typeof(object)),
                            Expression.Constant(null, typeof(object))
                        })),
                    notNullBlock));
            }
            else
            {
                VariableExpression c = Expression.Variable(typeof(object));
                bind.Append(Expression.Assign(c, Expression.Convert(walk.Field, typeof(object))));

                BlockExpression notNullBlock = Expression.Block();
                AppendBindOnInstance(notNullBlock, parentPlan.DeepObjParam, nextLevel, c, walk.BindMethodEmitter);

                bind.Append(Expression.IfThen(
                    Expression.Not(Expression.Call(_referenceEqualsMethod,
                        new Expression[]
                        {
                            c,
                            Expression.Constant(null, typeof(object))
                        })),
                    notNullBlock));
            }
        }

        private static void AppendBindOnInstance(BlockExpression block, Expression deepObjExpr, Expression nextLevel, Expression instance, MethodEmitter bindMethod)
        {
            block.Append(Expression.Call(instance, bindMethod, deepObjExpr, nextLevel));
        }

        private static int AllocateOrReuseTargetSlot(ScopePlan targetScope, string targetCode,
            FieldEmitter targetField, Type fieldType)
        {
            for (int i = 0; i < targetScope.ExportedSources.Count; i++)
            {
                if (string.Equals(targetScope.ExportedSources[i].MemberCode, targetCode, StringComparison.Ordinal))
                {
                    return i;
                }
            }

            int slot = targetScope.ExportedSources.Count;

            targetScope.ExportedSources.Add(new ExportedSource
            {
                MemberCode = targetCode,
                Field = targetField,
                FieldType = fieldType
            });

            return slot;
        }
        // @AI-Generated-End

        private Type HandleWildcardMember(AbstractTypeEmitter typeEmitter, MemberInDto parentMember, MemberInDto singleMember,
            int level, MemberInDto[] members, Dictionary<string, Type> typeCache, ScopePlan currentPlan, EmitContext ctx)
        {
            if (parentMember.MemberType is EnumMemberType.Enum or EnumMemberType.Object)
            {
                throw new InvalidOperationException(
                    $"Cannot create a type for wildcard member under an {parentMember.MemberType.ToString().ToLower()} type at level {level}, full code is {singleMember.Code}.");
            }

            if (singleMember.MemberType == EnumMemberType.MemberRef)
            {
                throw new InvalidOperationException(
                    $"MemberRef cannot be the single wildcard member at level {level}, full code is {singleMember.Code}.");
            }

            if (singleMember.MemberType is EnumMemberType.Array or EnumMemberType.Object)
            {
                Type type = CreateNestedType(typeEmitter, singleMember, level + 1, members, typeCache, currentPlan, ctx);

                return singleMember.MemberType == EnumMemberType.Array ? type.MakeArrayType() : type;
            }

            return GetTypeFromEnumMemberType(singleMember.MemberType, singleMember.Required);
        }

        private Type CreateEnumType(MemberInDto[] currentLevelMembers, MemberInDto parentMember, string prefix, int level)
        {
            Type underlyingType;

            EnumMemberType enumMemberType;

            try
            {
                enumMemberType = currentLevelMembers.Select(x => x.MemberType).Distinct().Single();
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException(
                    "Multiple member types found at the same level, which is not supported.", ex);
            }

            switch (enumMemberType)
            {
                case EnumMemberType.Byte:
                    underlyingType = typeof(byte);
                    break;
                case EnumMemberType.SByte:
                    underlyingType = typeof(sbyte);
                    break;
                case EnumMemberType.Int16:
                    underlyingType = typeof(short);
                    break;
                case EnumMemberType.UInt16:
                    underlyingType = typeof(ushort);
                    break;
                case EnumMemberType.Int32:
                    underlyingType = typeof(int);
                    break;
                case EnumMemberType.UInt32:
                    underlyingType = typeof(uint);
                    break;
                case EnumMemberType.Int64:
                    underlyingType = typeof(long);
                    break;
                case EnumMemberType.UInt64:
                    underlyingType = typeof(ulong);
                    break;
                default:
                    throw new InvalidOperationException(
                        $"Invalid member type for enum: {enumMemberType} at level {level}, full code is {parentMember.Code}.");
            }

            HashSet<string> hashSet = new();
            HashSet<object> enumValues = new();

            EnumEmitter enumEmitter =
                _emitter.DefineEnum($"Enum_{_regex.Replace(parentMember.Code, "_")}_{Guid.NewGuid():N}",
                    TypeAttributes.Public, underlyingType);

            enumEmitter.DefineCustomAttribute<FlagsAttribute>();

            foreach (MemberInDto member in currentLevelMembers)
            {
                string code = ExtractMemberCode(member.Code, prefix, level);

                ValidateMemberCode(code, member.Code, level, hashSet);

                object enumValue;

                try
                {
                    enumValue = Mapper.Map(member.DefaultValue, underlyingType);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException(
                        $"Enum member code is not a valid {underlyingType.Name} value: {member.DefaultValue} at level {level}, full code is {member.Code}.",
                        ex);
                }

                if (enumValues.Add(enumValue))
                {
                    enumEmitter.DefineLiteral(code, enumValue);
                }
                else
                {
                    throw new InvalidOperationException(
                        $"Duplicate enum value detected: {enumValue} for member code: {member.Code} at level {level}.");
                }
            }

            Type enumType = enumEmitter.CreateType();

            return parentMember.Required ? enumType : typeof(Nullable<>).MakeGenericType(enumType);
        }

        private Type CreateClassType(AbstractTypeEmitter typeEmitter, MemberInDto[] currentLevelMembers, MemberInDto parentMember,
            string prefix, int level, MemberInDto[] allMembers, Dictionary<string, Type> typeCache,
            ScopePlan parentPlan, EmitContext ctx)
        {
            // @AI-Generated by Copilot 2026-04-28 17:00:00
            NestedClassEmitter classEmitter = typeEmitter.DefineNestedType(
                $"{_regex.Replace(parentMember.Code, "_")}_Type",
                TypeAttributes.NestedPublic | TypeAttributes.Class | TypeAttributes.Sealed,
                typeof(object),
                new[] { typeof(IMemberRefBinder) });

            ScopePlan childPlan = new() { TypeEmitter = classEmitter, IsRoot = false, Depth = parentPlan.Depth + 1 };
            ctx.AllPlans.Add(childPlan);
            DefineBinderSkeleton(childPlan);

            AddPropertiesToClass(classEmitter, currentLevelMembers, prefix, level, allMembers, typeCache, childPlan, ctx);
            // @AI-Generated-End

            return classEmitter.UncompiledType;
        }

        // @AI-Generated by Copilot 2026-04-28 20:30:00
        /// <summary>
        /// 仅创建嵌套类外壳与对应 <see cref="ScopePlan"/>（含 Binder 骨架），不递归填充成员。
        /// 调用方需在递归子成员前向 <paramref name="ctx"/> 与 typeCache 注册祖先字段，方可让后代 MemberRef 反向定位。
        /// </summary>
        private (NestedClassEmitter shell, ScopePlan childPlan) CreateClassShell(AbstractTypeEmitter parentEmitter,
            MemberInDto parentMember, ScopePlan parentPlan, EmitContext ctx)
        {
            NestedClassEmitter classEmitter = parentEmitter.DefineNestedType(
                $"{_regex.Replace(parentMember.Code, "_")}_Type",
                TypeAttributes.NestedPublic | TypeAttributes.Class | TypeAttributes.Sealed,
                typeof(object),
                new[] { typeof(IMemberRefBinder) });

            ScopePlan childPlan = new() { TypeEmitter = classEmitter, IsRoot = false, Depth = parentPlan.Depth + 1 };
            ctx.AllPlans.Add(childPlan);
            DefineBinderSkeleton(childPlan);

            return (classEmitter, childPlan);
        }

        /// <summary>
        /// 判定 <paramref name="parent"/> 在 <paramref name="childLevel"/> 层是否对应一个"非通配的常规类"成员集合。
        /// 通配（单一 "*" 成员）由 <see cref="HandleWildcardMember"/> 单独处理，不需提前登记祖先字段。
        /// </summary>
        private static bool IsClassNonWildcard(MemberInDto parent, MemberInDto[] allMembers, int childLevel)
        {
            string prefix = parent.Code + ".";
            MemberInDto[] children = Array.FindAll(allMembers,
                m => m.Level == childLevel && m.Code.StartsWith(prefix));

            if (children.Length == 0)
            {
                return false;
            }

            if (children.Length == 1)
            {
                string code = ExtractMemberCode(children[0].Code, prefix, childLevel);

                if (code == "*")
                {
                    return false;
                }
            }

            return true;
        }
        // @AI-Generated-End

        private void AddPropertiesToClass(AbstractTypeEmitter typeEmitter, MemberInDto[] members, string prefix, int level,
            MemberInDto[] allMembers, Dictionary<string, Type> typeCache,
            ScopePlan currentPlan, EmitContext ctx)
        {
            HashSet<string> hashSet = new();
            // @AI-Generated by Copilot 2026-04-28 17:00:00
            Dictionary<string, MethodEmitter> gettersByCode = new(StringComparer.Ordinal);
            // 同层处理顺序：① 简单类型 ② Object/Array（递归） ③ MemberRef。
            MemberInDto[] orderedMembers = members
                .OrderBy(m => m.MemberType == EnumMemberType.MemberRef ? 2
                    : m.MemberType is EnumMemberType.Object or EnumMemberType.Array ? 1
                    : 0)
                .ToArray();
            // @AI-Generated-End

            Dictionary<MemberInDto, ScopePlan> childPlansByMember = new();

            foreach (MemberInDto member in orderedMembers)
            {
                string code = ExtractMemberCode(member.Code, prefix, level);

                ValidateMemberCode(code, member.Code, level, hashSet);

                Type enumMemberType;
                string memberRefImmediateTarget = null;
                string memberRefLeafTarget = null;
                bool isCrossScopeMemberRef = false;

                if (member.MemberType == EnumMemberType.MemberRef)
                {
                    // @AI-Generated by Copilot 2026-04-28 18:00:00
                    (enumMemberType, memberRefImmediateTarget, memberRefLeafTarget) =
                        ResolveMemberRefType(member, allMembers, typeCache, level);

                    string refParent = GetParentCode(member.Code);
                    string targetParent = GetParentCode(memberRefImmediateTarget);

                    bool sameScope = string.Equals(refParent, targetParent, StringComparison.Ordinal);

                    if (sameScope)
                    {
                        if (!gettersByCode.TryGetValue(memberRefImmediateTarget, out MethodEmitter targetGetter))
                        {
                            throw new InvalidOperationException(
                                $"MemberRef target {memberRefImmediateTarget} getter not yet defined when processing {member.Code}.");
                        }

                        MethodEmitter newGetter = DefineMemberRefDelegationProperty(typeEmitter, member, code,
                            enumMemberType, targetGetter);

                        gettersByCode[member.Code] = newGetter;
                        ctx.GettersByCode[member.Code] = newGetter;
                        ctx.ScopeByMemberCode[member.Code] = currentPlan;
                        ctx.TypesByMemberCode[member.Code] = enumMemberType;
                        typeCache[member.Code] = enumMemberType;

                        continue;
                    }

                    isCrossScopeMemberRef = true;
                    // @AI-Generated-End
                }
                else if (member.MemberType is EnumMemberType.Enum or EnumMemberType.Array or EnumMemberType.Object)
                {
                    // @AI-Generated by Copilot 2026-04-28 20:30:00
                    // Object/Array 的非通配类成员需要提前在 typeCache / FieldsByCode 中登记，
                    // 这样递归处理子成员时，后代里 MemberRef 才能反向引用到祖先（A.B.C → A）。
                    if (member.MemberType is EnumMemberType.Object or EnumMemberType.Array
                        && IsClassNonWildcard(member, allMembers, level + 1))
                    {
                        (NestedClassEmitter shell, ScopePlan childPlan) =
                            CreateClassShell(typeEmitter, member, currentPlan, ctx);

                        Type shellType = shell.UncompiledType;
                        Type ancestorPropType = member.MemberType == EnumMemberType.Array
                            ? shellType.MakeArrayType()
                            : shellType;

                        typeCache[member.Code] = ancestorPropType;

                        (PropertyEmitter _, MethodEmitter ancestorGetter, FieldEmitter ancestorField) =
                            DefineProperty(typeEmitter, member, code, ancestorPropType, null);

                        gettersByCode[member.Code] = ancestorGetter;
                        ctx.GettersByCode[member.Code] = ancestorGetter;
                        ctx.ScopeByMemberCode[member.Code] = currentPlan;
                        ctx.TypesByMemberCode[member.Code] = ancestorPropType;
                        ctx.FieldsByCode[member.Code] = ancestorField;

                        string nestedPrefix = member.Code + ".";
                        MemberInDto[] childLevelMembers = Array.FindAll(allMembers,
                            m => m.Level == level + 1 && m.Code.StartsWith(nestedPrefix));

                        AddPropertiesToClass(shell, childLevelMembers, nestedPrefix, level + 1,
                            allMembers, typeCache, childPlan, ctx);

                        if (childPlan.HasWork)
                        {
                            currentPlan.ChildWalks.Add(new ChildWalk
                            {
                                Field = ancestorField,
                                PropertyClrType = ancestorPropType,
                                IsArray = member.MemberType == EnumMemberType.Array,
                                BindMethodEmitter = childPlan.BindRecursiveMethod
                            });
                        }

                        continue;
                    }
                    // @AI-Generated-End

                    int planCountBefore = ctx.AllPlans.Count;

                    Type nestedType = CreateNestedType(typeEmitter, member, level + 1, allMembers, typeCache, currentPlan, ctx);

                    enumMemberType = member.MemberType == EnumMemberType.Array
                        ? nestedType.MakeArrayType()
                        : nestedType;

                    if (member.MemberType is EnumMemberType.Object or EnumMemberType.Array
                        && ctx.AllPlans.Count > planCountBefore)
                    {
                        ScopePlan addedPlan = ctx.AllPlans[planCountBefore];

                        childPlansByMember[member] = addedPlan;
                    }
                }
                else
                {
                    enumMemberType = GetTypeFromEnumMemberType(member.MemberType, member.Required);
                }

                typeCache[member.Code] = enumMemberType;

                // @AI-Generated by Copilot 2026-04-28 18:00:00
                (PropertyEmitter propEmitter, MethodEmitter getterEmitter, FieldEmitter fieldEmitter) = DefineProperty(typeEmitter, member, code,
                    enumMemberType, isCrossScopeMemberRef ? memberRefImmediateTarget : null);

                gettersByCode[member.Code] = getterEmitter;
                ctx.GettersByCode[member.Code] = getterEmitter;
                ctx.ScopeByMemberCode[member.Code] = currentPlan;
                ctx.TypesByMemberCode[member.Code] = enumMemberType;

                // 只为非 MemberRef 叶子记录字段，后续跨作用域 Ref 从叶子字段读源值。
                if (member.MemberType != EnumMemberType.MemberRef)
                {
                    ctx.FieldsByCode[member.Code] = fieldEmitter;
                }

                if (isCrossScopeMemberRef)
                {
                    if (!ctx.ScopeByMemberCode.TryGetValue(memberRefLeafTarget, out ScopePlan targetScope))
                    {
                        throw new InvalidOperationException(
                            $"MemberRef cross-scope target {memberRefLeafTarget} has not been generated yet, declared at {member.Code}.");
                    }

                    if (targetScope == currentPlan)
                    {
                        throw new InvalidOperationException(
                            $"MemberRef cross-scope target {memberRefImmediateTarget} resolved to current scope, declared at {member.Code}.");
                    }

                    // 跨作用域 MemberRef 仅允许指向祖先作用域中的成员；指向平级兄弟分支无法在运行时定位。
                    string refParent = GetParentCode(member.Code);
                    string targetLeafParent = GetParentCode(memberRefLeafTarget);

                    if (!IsAncestorOrSelfScope(targetLeafParent, refParent))
                    {
                        throw new InvalidOperationException(
                            $"MemberRef cross-scope target {memberRefLeafTarget} is on a sibling branch of {member.Code}; " +
                            $"only ancestor or same-scope targets are supported.");
                    }

                    if (!ctx.FieldsByCode.TryGetValue(memberRefLeafTarget, out FieldEmitter targetField))
                    {
                        throw new InvalidOperationException(
                            $"MemberRef cross-scope target {memberRefLeafTarget} has no backing field; only non-MemberRef leaves are supported as cross-scope sources.");
                    }

                    Type targetType = ctx.TypesByMemberCode[memberRefLeafTarget];

                    int slot = AllocateOrReuseTargetSlot(targetScope, memberRefLeafTarget, targetField, targetType);

                    currentPlan.LocalCrossRefs.Add(new LocalCrossRef
                    {
                        Field = fieldEmitter,
                        PropertyType = enumMemberType,
                        TargetScope = targetScope,
                        TargetSlot = slot
                    });
                }
                else if (childPlansByMember.TryGetValue(member, out ScopePlan childPlan))
                {
                    if (childPlan.HasWork)
                    {
                        currentPlan.ChildWalks.Add(new ChildWalk
                        {
                            Field = fieldEmitter,
                            PropertyClrType = enumMemberType,
                            IsArray = member.MemberType == EnumMemberType.Array,
                            BindMethodEmitter = childPlan.BindRecursiveMethod
                        });
                    }
                }
                // @AI-Generated-End
            }
        }

        // @AI-Generated by Copilot 2026-04-28 18:00:00
        private static bool HasAnyWork(ScopePlan plan)
        {
            if (plan.HasWork)
            {
                return true;
            }

            foreach (ChildWalk walk in plan.ChildWalks)
            {
                // ChildWalks already represent recursive work; HasWork covers it.
                _ = walk;
            }

            return false;
        }
        // @AI-Generated-End

        // @AI-Generated by Copilot 2026-04-28 10:00:00
        private (Type type, string immediateTargetCode, string leafTargetCode) ResolveMemberRefType(MemberInDto refMember,
            MemberInDto[] allMembers, Dictionary<string, Type> typeCache, int level)
        {
            if (string.IsNullOrWhiteSpace(refMember.DefaultValue))
            {
                throw new InvalidOperationException(
                    $"MemberRef requires DefaultValue (target member id) at level {level}, full code is {refMember.Code}.");
            }

            HashSet<long> visited = new();
            MemberInDto current = refMember;
            MemberInDto immediateTarget = ResolveMemberRefTargetById(refMember, refMember.DefaultValue, allMembers);
            MemberInDto next = immediateTarget;

            while (true)
            {
                if (!visited.Add(current.Id))
                {
                    throw new InvalidOperationException(
                        $"Circular MemberRef chain detected starting at {refMember.Code}.");
                }

                if (next.MemberType != EnumMemberType.MemberRef)
                {
                    if (!typeCache.TryGetValue(next.Code, out Type resolved))
                    {
                        throw new InvalidOperationException(
                            $"MemberRef target {next.Code} type has not been generated yet (only ancestor or earlier-sibling targets are supported), declared at {refMember.Code}.");
                    }

                    return (resolved, immediateTarget.Code, next.Code);
                }

                current = next;

                if (string.IsNullOrWhiteSpace(next.DefaultValue))
                {
                    throw new InvalidOperationException(
                        $"MemberRef chain broken at {next.Code}: DefaultValue is empty.");
                }

                next = ResolveMemberRefTargetById(refMember, next.DefaultValue, allMembers);
            }
        }

        private static MemberInDto ResolveMemberRefTargetById(MemberInDto refMember, string idText, MemberInDto[] allMembers)
        {
            if (!long.TryParse(idText, out long targetId))
            {
                throw new InvalidOperationException(
                    $"MemberRef DefaultValue must be the target member id (long): '{idText}', declared at {refMember.Code}.");
            }

            return Array.Find(allMembers, m => m.Id == targetId)
                ?? throw new InvalidOperationException(
                    $"MemberRef target member id not found: {targetId}, declared at {refMember.Code}.");
        }
        // @AI-Generated-End

        // @AI-Generated by Copilot 2026-04-28 17:00:00
        private static string GetParentCode(string fullCode)
        {
            int idx = fullCode.LastIndexOf('.');

            return idx < 0 ? string.Empty : fullCode.Substring(0, idx);
        }

        /// <summary>
        /// 判断 <paramref name="ancestorParent"/> 标识的作用域是否是 <paramref name="descendantParent"/> 的祖先（或自身）。
        /// 作用域以"父成员代码"标识，根作用域为空字符串。
        /// </summary>
        private static bool IsAncestorOrSelfScope(string ancestorParent, string descendantParent)
        {
            if (ancestorParent.Length == 0)
            {
                return true;
            }

            if (string.Equals(ancestorParent, descendantParent, StringComparison.Ordinal))
            {
                return true;
            }

            return descendantParent.Length > ancestorParent.Length
                && descendantParent.StartsWith(ancestorParent, StringComparison.Ordinal)
                && descendantParent[ancestorParent.Length] == '.';
        }
        // @AI-Generated-End

        private static string ExtractMemberCode(string fullCode, string prefix, int level)
        {
            return level == 0 ? fullCode : fullCode.Substring(prefix.Length);
        }

        private static void ValidateMemberCode(string code, string fullCode, int level, HashSet<string> hashSet)
        {
            if (_regex.IsMatch(code))
            {
                string context = level == 0 ? "root" : $"level {level}";

                throw new InvalidOperationException(
                    $"Member code contains invalid characters: {code} at {context}, full code is {fullCode}.");
            }

            if (!hashSet.Add(code))
            {
                string context = level == 0 ? "root" : $"level {level}";

                throw new InvalidOperationException(
                    $"Duplicate member code detected: {code} at {context}, full code is {fullCode}.");
            }
        }

        // @AI-Generated by Copilot 2026-04-28 17:00:00
        private static MethodEmitter DefineMemberRefDelegationProperty(AbstractTypeEmitter typeEmitter, MemberInDto member,
            string propertyName, Type propertyType, MethodEmitter targetGetter)
        {
            MethodEmitter getterEmitter = typeEmitter.DefineMethod($"get_{propertyName}",
                MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.HideBySig, propertyType);

            Expression call = Expression.Call(targetGetter);

            Expression body = call.RuntimeType == propertyType ? call : Expression.Convert(call, propertyType);

            getterEmitter.Append(body);

            PropertyEmitter propertyBuilder =
                typeEmitter.DefineProperty(propertyName, PropertyAttributes.None, propertyType);
            propertyBuilder.SetGetMethod(getterEmitter);

            propertyBuilder.SetCustomAttribute(new CustomAttributeBuilder(typeof(DescriptionAttribute).GetConstructor(new[] { typeof(string) }),
                new object[] { member.Description ?? member.Name ?? propertyName }));

            propertyBuilder.SetCustomAttribute(new CustomAttributeBuilder(typeof(DisplayNameAttribute).GetConstructor(new[] { typeof(string) }),
                new object[] { member.Name ?? propertyName }));

            return getterEmitter;
        }
        // @AI-Generated-End

        private static (PropertyEmitter property, MethodEmitter getter, FieldEmitter field) DefineProperty(AbstractTypeEmitter typeEmitter,
            MemberInDto member, string propertyName, Type propertyType, string memberRefTargetCode = null)
        {
            FieldEmitter fieldBuilder =
                typeEmitter.DefineField($"_{propertyName}", propertyType, FieldAttributes.Private);

            if (memberRefTargetCode is null && !string.IsNullOrEmpty(member.DefaultValue) && propertyType.IsSimple())
            {
                object defaultValue = Mapper.Map(member.DefaultValue, propertyType);

                if (defaultValue != null)
                {
                    fieldBuilder.DefaultValue = defaultValue;
                }
            }

            MethodEmitter getterEmitter = typeEmitter.DefineMethod($"get_{propertyName}",
                MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.HideBySig, propertyType);
            getterEmitter.Append(fieldBuilder);

            MethodEmitter setterEmitter = typeEmitter.DefineMethod($"set_{propertyName}",
                MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.HideBySig, typeof(void));
            ParameterEmitter parameterEmitter = setterEmitter.DefineParameter(propertyType, "value");
            setterEmitter.Append(Expression.Assign(fieldBuilder, parameterEmitter));

            PropertyEmitter propertyBuilder =
                typeEmitter.DefineProperty(propertyName, PropertyAttributes.None, propertyType);
            propertyBuilder.SetGetMethod(getterEmitter);
            propertyBuilder.SetSetMethod(setterEmitter);

            propertyBuilder.SetCustomAttribute(new CustomAttributeBuilder(typeof(DescriptionAttribute).GetConstructor(new[] { typeof(string) }),
                new object[] { member.Description ?? member.Name ?? propertyName }));

            propertyBuilder.SetCustomAttribute(new CustomAttributeBuilder(typeof(DisplayNameAttribute).GetConstructor(new[] { typeof(string) }),
                new object[] { member.Name ?? propertyName }));

            return (propertyBuilder, getterEmitter, fieldBuilder);
        }

        private static Type GetTypeFromEnumMemberType(EnumMemberType enumMemberType, bool required)
        {
            switch (enumMemberType)
            {
                case EnumMemberType.Boolean:
                    return required ? typeof(bool) : typeof(bool?);
                case EnumMemberType.Char:
                    return required ? typeof(char) : typeof(char?);
                case EnumMemberType.SByte:
                    return required ? typeof(sbyte) : typeof(sbyte?);
                case EnumMemberType.Byte:
                    return required ? typeof(byte) : typeof(byte?);
                case EnumMemberType.Int16:
                    return required ? typeof(short) : typeof(short?);
                case EnumMemberType.UInt16:
                    return required ? typeof(ushort) : typeof(ushort?);
                case EnumMemberType.Int32:
                    return required ? typeof(int) : typeof(int?);
                case EnumMemberType.UInt32:
                    return required ? typeof(uint) : typeof(uint?);
                case EnumMemberType.Int64:
                    return required ? typeof(long) : typeof(long?);
                case EnumMemberType.UInt64:
                    return required ? typeof(ulong) : typeof(ulong?);
                case EnumMemberType.Single:
                    return required ? typeof(float) : typeof(float?);
                case EnumMemberType.Double:
                    return required ? typeof(double) : typeof(double?);
                case EnumMemberType.Decimal:
                    return required ? typeof(decimal) : typeof(decimal?);
                case EnumMemberType.DateTime:
                    return required ? typeof(DateTime) : typeof(DateTime?);
                case EnumMemberType.String:
                    return typeof(string);
                case EnumMemberType.Enum:
                    return typeof(Enum);
                case EnumMemberType.Array:
                    return typeof(Array);
                case EnumMemberType.MemberRef:
                    return typeof(object);
                case EnumMemberType.Object:
                default:
                    return typeof(object);
            }
        }
    }
}
